POSICION: DB 16, 0
LONGITUDPALA: EQU 5
COLORPALA: EQU 2*8+2
CONTADOR: EQU $07FF
Pala_inicio
    CALL DIBUJARPALA
    CALL TECLADO
    CALL NUEVAPOSICION
    
    ; ----------------------
    ; Actualizar pelota aquí
    ;-----------------------
    
    CALL ESPERAR
    JR Pala_inicio
DIBUJARPALA:
    LD A, (POSICION + 1)
    OR A
    JR Z, DIBUJARPALA1
    LD C, 0
    CALL DIBUJARPALACOLOR
DIBUJARPALA1:
    LD A, (POSICION)
    LD C, COLORPALA
    CALL DIBUJARPALACOLOR
    RET
DIBUJARPALACOLOR:
    LD HL, $5B00 - 32
    LD D, 0
    LD E, A
    ADD HL, DE
    LD B, LONGITUDPALA
DIBUJARPALACOLOR1:
    LD (HL), C
    INC HL
    DJNZ DIBUJARPALACOLOR1
    RET
NUEVAPOSICION:
    LD A, B
    OR A
    RET Z
    LD  A, (POSICION)
    ADD B
    OR A ; A = A|A
    RET Z
    CP 32 - LONGITUDPALA
    RET NC
    LD B, A
    LD A, (POSICION)
    LD (POSICION + 1), A
    LD A, B
    LD (POSICION), A
    RET
ESPERAR:
    LD BC, CONTADOR
ESPERAR1:
    DEC BC
    LD A, B
    OR C
    JR NZ, ESPERAR1
    RET